jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # تثبيت Node.js لتشغيل npm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # حدد إصدار Node.js

      # تثبيت الحزم إذا كان package.json موجودًا
      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            npm install
          else
            echo "No package.json file found. Skipping npm install."
          fi

      - name: Build Bicep for linting
        uses: azure/CLI@v1
        with:
          inlineScript: az config set bicep.use_binary_from_path=false && az bicep build -f infra/main.bicep --stdout

      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@preview
        id: msdo
        continue-on-error: true
        with:
          tools: templateanalyzer
        env:
          GDN_TEMPLATEANALYZER_VERBOSE: 1

      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
